version: '3.3'

services:
  stats:
    build: ./stats
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  nginx:
    image: nginx
    restart: on-failure
    links:
      - main-server
      - websocket
    ports:
      - "80:9000"
      - "3999:7000"

  main-server:
    build: ./server
    restart: on-failure
    ports:
      - "8000:8099"
    environment:
      - NAME=Server

  websocket:
    build: ./websocket
    restart: on-failure
    ports:
      - "3111:3000"
    links:
      - redis

  redis:
    image: redis:alpine
    restart: on-failure
    expose:
      - "6379"

  mysql:
    image: mysql:5.7
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass01
      - MYSQL_USER=viewer
      - MYSQL_PASSWORD=pass02
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - mysql:db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    environment:
      - PMA_HOST=db 
      - PMA_PORT=3306
      #- PMA_ARBITRARY=1
    ports:
      - 8081:80
    links:
      - mysql:db

  mantisbt:
    image: lucasbasquerotto/mantisbt
    restart: on-failure
    ports:
      - 8082:80
    links:
      - mysql:db

  wordpress:
    image: wordpress:latest
    restart: on-failure
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - "8083:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress

volumes:
  db_data:
